// Code Connect — Icons / Emoji
// Auto-generated by scripts/generate-code-connect.js — do not edit by hand

import figma from "@figma/code-connect";

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14183",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-zzz"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14161",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-snowman"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14058",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-wink-tongue"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13980",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sunglasses"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13927",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-smile-wink"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13877",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-smile"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13827",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sad-tear"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13774",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-profile"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13743",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-neutral"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13671",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-grinning"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13646",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-angry"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13584",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-alien"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13799",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sad"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13852",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sleep"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13902",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-smile-beam"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13696",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-lol"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13718",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-mouthless"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14033",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sweat"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14005",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-surprised"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14080",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-ghost"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13615",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-add-reaction"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14105",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-poop"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-14130",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-skull"/></svg>`,
  }
);

figma.connect(
  "https://www.figma.com/design/92ZwLCANCyRKezlcuQLOBW/Engu-Design-System?node-id=1200-13952",
  {
    example: () => `<svg viewBox="0 0 24 24" fill="none"><use href="assets/icons/engu-icons-sprite.svg#engu-emoji-sticker-smirk"/></svg>`,
  }
);
